default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: project2
  username: postgres
  password: 123456

test:
  <<: *default
  database: project2_test
  username: postgres
  password: 123456
