module Constant
  LIMIT_PER_PAGE = 5
  TOP_TEACHERS_LIMIT = 5
  RECENT_LOCKED_USERS_LIMIT = 5
  DASHBOARD_MONTH_RANGE = 5
  REVIEW_ROLE_TEACHER = 0
  REVIEW_ROLE_STUDENT = 1
  ROLE_STUDENT = "student"
  ROLE_TEACHER = "teacher"
  ROLE_ADMIN = "admin"
  REQUEST_STATUS_OPEN = "open"
  REQUEST_STATUS_ACCEPTED = "accepted"
  REQUEST_STATUS_STUDYING = "studying"
  REQUEST_STATUS_REJECTED = "rejected"
  REQUEST_STATUS_CLOSED = "closed"
  TIMETABLE_STATUS_OPEN = "open"
  TIMETABLE_STATUS_DEPOSIT = "deposit"
  TIMETABLE_STATUS_CLOSED = "closed"
  TUITION_STATUS_NEW = "new"
  TUITION_STATUS_DEPOSIT = "deposit"
  TUITION_STATUS_PAYED = "payed"
  SUPPORT_STATUS_OPEN = "open"
  SUPPORT_STATUS_PROCESSING = "processing"
  SUPPORT_STATUS_CLOSED = "closed"
  SUPPORT_CATEGORY_ACCOUNT = "account"
  SUPPORT_CATEGORY_PAYMENT = "payment"
  SUPPORT_CATEGORY_OTHER = "other"
end
